### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "zzq",
    "email": "zzq@163.com",
    "password": "123456"
}

### signup another user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "alice",
    "email": "alice@163.com",
    "password": "123456"
}


### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
"workspace": "acme", "fullname": "Bob Hua", "email": "bob@acme.org", "password": "123456"
}

### signup user(invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "zzq@163.com",
    "password": "a123456"
}

### signin user(valid)


# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "zzq@163.com",
    "password": "123456"
}

@token = {{signin.response.body.token}}


### signin user(valid)
# @name signin1
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "bob@acme.org",
    "password": "123456"
}

@token1 = {{signin1.response.body.token}}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "project X",
    "members": [1,2],
    "public": false
}

### create direct chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
"members": [1, 2], "public": false
}

### create chats without me
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token1}}

{
"name": "project Y", "members": [2, 3], "public": false
}

### create direct chat without me
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token1}}

{
"members": [2, 3], "public": false
}

### get chat list

GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### get user list

GET http://localhost:6688/api/users
Authorization: Bearer {{token}}


### update chat
PATCH http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "chat1222",
    "members": [1,2, 3, 4],
    "public": true
}


### delete chat
DELETE http://localhost:6688/api/chats/1
Authorization: Bearer {{token}}


### get chat list
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}


### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}


### upload files
POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="README.md"
Content-Type: application/octet-stream

< /Users/zhouzhangqi/rust-camp/chat/chat_server/README.md
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"

hello world
--MyBoundary--


### get file
GET http://localhost:6688/api/files/1/2aa/e6c/35c94fcfb415dbe95f408b9ce91ee846ed.txt
Authorization: Bearer {{token}}


### get file with token
GET http://localhost:6688/api/files/1/2aa/e6c/35c94fcfb415dbe95f408b9ce91ee846ed.txt?token={{token}}

### send a message
POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Hello, World!",
    "files": []
}

### get messages

GET http://localhost:6688/api/chats/1/messages?limit=6&last_id=5
Authorization: Bearer {{token}}


### get messages

GET http://localhost:6688/api/chats/1/messages
Authorization: Bearer {{token}}

### signin user(invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "zzq@163.com",
    "password": "123456"
}


### create chat agent
POST http://localhost:6688/api/chats/1/agents
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "translator",
    "type": "proxy",
    "adapter": "ollama",
    "model": "llama3.2",
    "prompt": "You're the world's best translator. You understand English and Chinese well, also their culture and idioms. You will translate user input between English and Chinese. If the original text is English, you will translate it to elegant, authentic Simplified Chinese. If the original text is Chinese, you will translate it to elegant, authentic English. Only return the translated sentences, no other text or comments. below are the text to translate:"
}


### update agent
PATCH http://localhost:6688/api/chats/1/agents
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 3,
    "prompt": "You are a helpful assistant.",
    "args": "{}"
}

### list agents
GET http://localhost:6688/api/chats/1/agents
Authorization: Bearer {{token}}



### Send chinese message
POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "你好，今天工作幸苦了",
    "files": []
}


### Send english message
POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Hello, how are you?",
    "files": []
}
